name: Deploy WhatsApp Movie Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the Node.js version you prefer

    - name: Install dependencies
      run: npm install

    - name: Run bot
      run: npm start
